# ansible-configured
- name: Fail if missing value
  fail:
    msg: 
      - "Please specify the frequence in Mhz of the biggest CPU in the cluster if you want to enable reservation."
      - "If you are running the script for a production envitonment this is HIGLY suggested."
  when: 
    - enable_reservation|bool
    - cpu_biggest is undefined or cpu_biggest <= 1

- name: Fail if not enought nodes
  fail:
    msg: 
      - "You need at least 3 master nodes and 1 worker"
  when: 
    - (vm_hosts | selectattr("type", "equalto", "master") | list | count) < 3
    - (vm_hosts | selectattr("type", "equalto", "worker") | list | count) < 1


- name: Fail if not filled the network variables
  fail:
    msg: 
      - "Check your variables, you need a Network a nermask a gateway and at least one dns"
  when: 
    - hosts_defaults.network.name is undefined
    - hosts_defaults.network.mask is undefined
    - hosts_defaults.network.gw is undefined
    - hosts_defaults.network.dns[0] is undefined

# - name: Check how many servers are in group webserver
#   fail:
#     msg: 
#       - "You Should have at least one webserver."
#   when: 
#     - groups.webserver| list | count == 0


# Pause to get some sensitive input.
- name: I need at least one webserver
  when: groups.webserver| list | count == 0
  block:
    - name: Prompt for a choise
      pause:
        prompt: "      You have specified no server in webserver group.\n      I need at least a reachable webserver.\n      I will use myself (the host running this playbook) as one. \n      Reply yes if you wish to continue"
        echo: Yes
      register: reply
      delegate_to: localhost

    - name: Check reply
      when: reply.user_input|lower != 'yes'
      fail:
        msg: "Failing as requested"


    # add localhost to webservers if none is provided
    - name: Add host to group 'webservers' if none is provided
      delegate_to: localhost
      add_host:
        name: "{{ansible_fqdn}}"
        groups: webserver
