- name: Check if installer already exist
  delegate_to: localhost  
  register: installer_bin
  stat:
    path: "{{playbook_dir}}/tmp/bin/openshift-install"

- name: Check if configuration already exist
  delegate_to: localhost  
  register: install_config
  stat:
    path: "{{playbook_dir}}/tmp/cluster_conf/install-config.yaml"

- name: Check if manifest already exist
  delegate_to: localhost  
  register: manifest_dir
  stat:
    path: "{{playbook_dir}}/tmp/cluster_conf/manifests/"

- name: Check if ignition already exist
  delegate_to: localhost  
  register: master_ign
  stat:
    path: "{{playbook_dir}}/tmp/cluster_conf/master.ign"

- name: Check if ignition already exist
  delegate_to: localhost  
  register: installer_tgz
  stat:
    path: "{{playbook_dir}}/tmp/downloads/ocp_installer.tgz"


- name: Create base config path
  become: false
  delegate_to: localhost  
  loop:
    - "{{playbook_dir}}/tmp/downloads"
    - "{{playbook_dir}}/tmp/bin"
    - "{{playbook_dir}}/tmp/cluster_conf"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes

- name: Download Installer
  become: false
  delegate_to: localhost  
  when: not installer_tgz.stat.exists
  get_url:
    url: "{{ ocp_installer.installer }}"
    dest: "{{playbook_dir}}/tmp/downloads/ocp_installer.tgz"

- name: "Extract {{playbook_dir}}/tmp/downloads/ocp_installer.tgz in {{playbook_dir}}/tmp/bin"
  become: false
  delegate_to: localhost  
  when: not installer_bin.stat.exists
  unarchive:
    src: "{{playbook_dir}}/tmp/downloads/ocp_installer.tgz"
    dest: "{{playbook_dir}}/tmp/bin"

- name: Create configuration template
  become: false
  delegate_to: localhost  
  when: not install_config.stat.exists
  loop:
    - "{{playbook_dir}}/tmp/cluster_conf/install-config.yaml"
    - "{{playbook_dir}}/tmp/cluster_conf/install-config.yaml.keep"
  template:
    src: install-config.yaml.j2
    dest: "{{ item }}"

- name: Create Manifests
  become: false
  delegate_to: localhost  
  when: (not manifest_dir.stat.exists) and (not master_ign.stat.exists)
  shell: '{{playbook_dir}}/tmp/bin/openshift-install create manifests --dir="{{playbook_dir}}/tmp/cluster_conf"'

- name: Ensure Masters not schedulable
  become: false
  delegate_to: localhost  
  when: not master_ign.stat.exists
  lineinfile:
    path: "{{playbook_dir}}/tmp/cluster_conf/manifests/cluster-scheduler-02-config.yml"
    regexp: 'mastersSchedulable:'
    line: '  mastersSchedulable: false'

- name: Create Ignition
  become: false
  delegate_to: localhost  
  when: not master_ign.stat.exists
  shell: '{{playbook_dir}}/tmp/bin/openshift-install create ignition-configs --dir="{{playbook_dir}}/tmp/cluster_conf"'

