# ansible-configured
---


- name: Install Ansible's vmware_guest required libraryes
  delegate_to: localhost
  yum:
    name: 
      - python3-requests
      - python3-pip
    state: present

- name: Install python non rpm packages
  delegate_to: localhost
  pip:
    name: 
      - PyVmomi

- name: Create Directory in Datastore to host iPXE
  vsphere_file:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    datacenter: "{{ vcenter.datacenter }}"
    datastore:  "{{ vcenter.datastore }}"      
    path: "{{ ocp_installer.clustername }}"
    state: directory
  delegate_to: localhost
  ignore_errors: yes

- name: "Query a ipxe iso file on a datastore {{ ocp_installer.clustername }}/{{ hosts_defaults.iso }}"
  vsphere_file:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    datacenter: "{{ vcenter.datacenter }}"
    datastore:  "{{ vcenter.datastore }}"      
    path: "{{ ocp_installer.clustername }}/{{ hosts_defaults.iso }}"
    state: file
  delegate_to: localhost
  ignore_errors: yes
  register: ipxe_inuse

- name: Copy file to datastore
  when: ipxe_inuse.state == 'absent'
  vsphere_copy:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    datacenter: "{{ vcenter.datacenter }}"
    datastore:  "{{ vcenter.datastore }}"
    src: "{{playbook_dir}}/tmp/iso/rhcos_ipxe.iso"
    path: "{{ ocp_installer.clustername }}/{{ hosts_defaults.iso }}"
  delegate_to: localhost

- name: "Create a VM folder ({{ vcenter.folder }}) on datacenter {{ vcenter.datacenter }}"
  vcenter_folder:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    datacenter: "{{ vcenter.datacenter }}"
    folder_name: "{{ vcenter.folder }}"
    folder_type: vm
    state: present
  register: vm_folder_creation_result
  delegate_to: localhost

- name: "Create a Datastore folder ({{ ocp_installer.clustername }}) on datacenter {{ vcenter.datacenter }}"
  vcenter_folder:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    datacenter: "{{ vcenter.datacenter }}"
    folder_name: "{{ ocp_installer.clustername }}"
    folder_type: datastore
    state: present
  register: vm_folder_creation_result
  delegate_to: localhost

- name: Create a virtual machine from a template
  tags: vm
  loop: "{{ vm_hosts }}"
  vmware_guest:
    annotation: "{{ item.annotation | default('Openshift node ' + item.type) }}"
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    folder: "{{ vcenter.folder }}"
    name: "{{ item.vmname | default(item.hostname) }}"
    state: present
    datacenter: "{{ vcenter.datacenter }}"
    template: "{{ hosts_defaults.template if (item.install_method | default(hosts_defaults.install_method) == 'template') else Null }}"
    guest_id: "{{ item.guest_id | default(hosts_defaults[item.type]['guest_id']) }}"
    disk:
      - size_gb: "{{ item.disk | default(hosts_defaults[item.type]['disk']) }}"
        type: "{{ item.disktype | default(hosts_defaults[item.type]['disktype'])| default('thin') }}"
        datastore:  "{{ vcenter.datastore }}"
    hardware:
      nested_virt: "{{ item.nested_virt | default(hosts_defaults[item.type]['nested_virt']) }}"
      memory_mb: "{{ item.memory_mb | default(hosts_defaults[item.type]['memory_mb']) }}"
      num_cpus: "{{ item.num_cpus | default(hosts_defaults[item.type]['num_cpus']) }}"
      num_cpu_cores_per_socket: "{{ item.num_cpu_cores_per_socket | default(hosts_defaults[item.type]['num_cpu_cores_per_socket']) }}"
      mem_reservation: "{{ '0' if not enable_reservation else (item.memory_mb | default(hosts_defaults[item.type]['memory_mb'])) }}"
      memory_reservation_lock: "{{ 'True' if enable_reservation else 'False' }}"
      cpu_reservation: "{{ '0' if not enable_reservation else (vcenter.cpu_biggest * ( item.num_cpus | default(hosts_defaults[item.type]['num_cpus'])) * ( item.num_cpu_cores_per_socket | default(hosts_defaults[item.type]['num_cpu_cores_per_socket']))) }}"
    cdrom:
      type: iso
      iso_path: "{{ item.iso | default('[' + vcenter.datastore + ']' + ocp_installer.clustername + '/' + hosts_defaults.iso) }}"
    customvalues:
      - key: guestinfo.ipxe.hostname
        value: "{{ item.hostname }}"
      - key: guestinfo.ipxe.ignition
        value: "{{ item.ignition | default(hosts_defaults[item.type]['ignition']) }}"
      - key: guestinfo.ipxe.net0.ip
        value: "{{ item.network.ip }}"
      - key: guestinfo.ipxe.net0.netmask
        value: "{{ item.network.mask |  default(hosts_defaults.network.mask) }}"
      - key: guestinfo.ipxe.net0.gateway
        value: "{{ item.network.gw |  default(hosts_defaults.network.gw) }}"
      - key: guestinfo.ipxe.fileserver
        value: "http://{{ hostvars[ groups.webserver[0] ]['ansible_fqdn'] }}:8080"
      - key: guestinfo.ipxe.dns
        value: "{{ item.network.dns[0] |  default(hosts_defaults.network.dns[0]) | default(Null) }}"
      - key: guestinfo.ipxe.dns1
        value: "{{ item.network.dns[0] |  default(hosts_defaults.network.dns[0]) | default(Null) }}"
      - key: guestinfo.ipxe.dns2
        value: "{{ item.network.dns[1] |  default(hosts_defaults.network.dns[1]) | default(Null) }}"
      - key: guestinfo.ipxe.dns3
        value: "{{ item.network.dns[2] |  default(hosts_defaults.network.dns[2]) | default(Null) }}"
      - key: guestinfo.ipxe.kernel-installer
        value: "{{ item.kernelimg |  default(hosts_defaults.kernelimg) | default('kernel') }}"
      - key: guestinfo.ipxe.initrd-installer
        value: "{{ item.initramfs |  default(hosts_defaults.initramfs) | default('initramfs.img') }}"
      - key: guestinfo.ipxe.rhcos-image
        value: "{{ item.rhcosimage | default(hosts_defaults.rhcosimage) | default('rhcos.raw.gz') }}" 
      - key: guestinfo.ipxe.disk
        value: "{{ item.disk |  default(hosts_defaults['disk']) | default('sda') }}"
      - key: guestinfo.ipxe.net_interface
        value: "{{ item.network.interface |  default(hosts_defaults['network']['interface']) | default('ens192') }}"
      - key: guestinfo.ipxe.menu_default
        value: "{{ item.install_method |  default(hosts_defaults.install_method) }}"
      - key: disk.EnableUUID
        value: "TRUE"
      - key: sched.cpu.latencySensitivity
        value: "{{ 'high' if enable_reservation else 'normal' }}"
    networks:
    - name: "{{ item.network.name |  default(hosts_defaults['network']['name']) }}"
  delegate_to: localhost
  register: deploy

- name: Change virtual machine's boot order and related parameters
  tags: vm
  loop: "{{ vm_hosts }}"
  vmware_guest_boot_manager:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    name: "{{ item.vmname | default(item.hostname) }}"
    boot_delay: 2000
    enter_bios_setup: False
    boot_retry_enabled: True
    boot_retry_delay: 10000
    boot_firmware: bios
    # secure_boot_enabled: False
    boot_order:
      - cdrom
      - disk
  delegate_to: localhost
  register: vm_boot_order

- name: Power on Machines
  tags: vm
  loop: "{{ vm_hosts }}"
  vmware_guest:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    name: "{{ item.vmname | default(item.hostname) }}"
    state: poweredon
    datacenter: "{{ vcenter.datacenter }}"
  delegate_to: localhost
  register: deploy  