- name: Delete Machines
  tags: vm
  loop: "{{ vm_hosts }}"
  when:
    - not ocp_vm_cleanup_preserve_vm|bool
  vmware_guest:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    folder: "{{ vcenter.folder }}"
    name: "{{ item.vmname | default(item.hostname) }}"
    state: "absent" 
    force: true
  delegate_to: localhost
  register: deploy

- name: Delete PXE image
  when:
    - not ocp_vm_cleanup_preserve_iso|bool
  vsphere_file:
    hostname: "{{ vcenter.host }}"
    username: "{{ vcenter.user }}"
    password: "{{ vcenter.password }}"
    validate_certs: "{{ vcenter.validate_certs }}"
    datacenter: "{{ vcenter.datacenter }}"
    datastore:  "{{ vcenter.datastore }}"      
    path: "{{ ocp_installer.clustername }}/{{ hosts_defaults.iso }}"
    state: absent
  delegate_to: localhost
  ignore_errors: yes
  register: ipxe_inuse

- name: Delete local tmp and config files
  when:
    - not ocp_vm_cleanup_preserve_tmp|bool
  loop:
    - "{{playbook_dir}}/tmp"
  file:
    path: "{{ item }}"
    state: absent
    force: yes