---
- name: Configuration coherence check
  when:
    - not ocp_vm_cleanup|bool
    - ocp_vm_check_conf|bool
  include_tasks: 00-set_facts_and_cfg_check.yml

- name: Environment check
  when: 
    - not ocp_vm_cleanup|bool
    - ocp_vm_check_env|bool
  include_tasks:  01-check_dns.yml

- name: Prepare WebServer
  when: 
    - ocp_installer.install_method != 'template'
    - not checks_only|bool
    - not ocp_vm_cleanup|bool
    - ocp_vm_create_webserver
    - "'webserver' in group_names"
  tags: 
   - web
   - nginx
  include_tasks: 10-nginx.yml

- name: Prepare HaProxy
  when: 
    - not checks_only|bool
    - not ocp_vm_cleanup|bool
    - ocp_vm_create_haproxy
    - "'haproxy' in group_names"
  tags: 
    - web
    - haproxy
  include_tasks: 20-haproxy.yml


- name: Create PXE Image
  when: 
    - ocp_installer.install_method != 'template'
    - not checks_only|bool
    - not ocp_vm_cleanup|bool
    - ocp_vm_create_ipxe
  tags: 
    - pxe
    - ipxe
    - iso
  include_tasks: 30-pxe.yml

- name: Create Grub Loaders
  when: 
    - ocp_installer.install_method == 'grub'
    - not checks_only|bool
    - not ocp_vm_cleanup|bool
    - ocp_vm_create_grub
  tags: 
    - pxe
    - grub
    - iso
  include_tasks: 31-grub.yml

- name: prepare installer
  when: 
    - not ocp_vm_cleanup|bool
    - not checks_only|bool
    - ocp_vm_prepare_installer|bool
  tags: 
    - installer
  include_tasks: 40-installer.yml

- name: transpile ignition
  when: 
    - ocp_installer.install_method == 'template'
    - not ocp_vm_cleanup|bool
    - not checks_only|bool
    - ocp_vm_transpile|bool
  tags: 
    - transpile
  include_tasks: 41-transpile.yml

- name: Create VMS
  when: 
    - not ocp_vm_cleanup|bool
    - not checks_only|bool
    - ocp_vm_create_vm|bool
  tags: 
    - vms
  include_tasks: 50-vms.yml

- name: Install Client
  when: 
    - not ocp_vm_cleanup|bool
    - not checks_only|bool
    - ocp_vm_install_client|bool
  tags: 
    - kubectl
    - oc
  include_tasks: 60-client.yml

- name: Cleanup
  when: 
  - ocp_vm_cleanup|bool
  - not checks_only|bool
  tags: 
    - debug
  include_tasks: 99-cleanup.yml