---
- hosts: all
  vars:
    ocp_vm_cleanup: True
  remote_user: root
  roles:
  - openshift4_vmware_infra_provisioner

- hosts: all
  vars:
    ocp_vm_cleanup: False
  remote_user: root
  roles:
  - openshift4_vmware_infra_provisioner
